upgrade setup and dependencies
lineupjs/lineupjs pull request #410
Opened 2021-02-27 15:24 UTC by sgratzl

**Prerequisites**:

* [x] Branch is up-to-date with the branch to be merged with, i.e. develop
* [x] Build is successful
* [x] Code is cleaned up and formatted 
* [x] Tested with Firefox ESR, latest Firefox, latest Chrome, Edge 18

### Summary
 
upgrades the dependencies and setup (using yarn2 berry)

note: 
 * I couldn't figure out how to combine cypress with typescript such that it finds it. Thus, you have to compile them first using `yarn run cy:compile`

2021-03-08 09:59 UTC, thinkh requested changes
Currently, I'm unable to upgrade/setup my development environment. It looks like switching to yarn in WSL 2 does not work for me.

I'm following the installation steps from the [updated README.md](https://github.com/lineupjs/lineupjs/blob/sgratzl/upgrade/README.md#development-environment):

```
❯ npm i -g yarn

> yarn@1.22.10 preinstall /home/holger/.nvm/versions/node/v12.13.1/lib/node_modules/yarn
> :; (node ./preinstall.js > /dev/null 2>&1 || true)

/home/holger/.nvm/versions/node/v12.13.1/bin/yarn -> /home/holger/.nvm/versions/node/v12.13.1/lib/node_modules/yarn/bin/yarn.js
/home/holger/.nvm/versions/node/v12.13.1/bin/yarnpkg -> /home/holger/.nvm/versions/node/v12.13.1/lib/node_modules/yarn/bin/yarn.js
+ yarn@1.22.10
updated 1 package in 0.795s

❯ yarn set version latest
Resolving latest to a url...
Downloading https://github.com/yarnpkg/yarn/releases/download/v1.22.10/yarn-1.22.10.js...
Saving it into /home/holger/w/lineupjs/lineupjs/.yarn/releases/yarn-1.22.10.cjs...
Updating /home/holger/w/lineupjs/lineupjs/.yarnrc...
Done!

❯ cat .yarnrc_patch.yml >> .yarnrc.yml

❯ yarn install
TypeError: Cannot read property 'yarnPath' of null
    at loadRcFile (/home/holger/.nvm/versions/node/v12.13.1/lib/node_modules/yarn/lib/cli.js:56946:49)
    at /home/holger/.nvm/versions/node/v12.13.1/lib/node_modules/yarn/lib/cli.js:56917:14
    at /home/holger/.nvm/versions/node/v12.13.1/lib/node_modules/yarn/lib/cli.js:100892:14
    at Array.map (<anonymous>)
    at parseRcPaths (/home/holger/.nvm/versions/node/v12.13.1/lib/node_modules/yarn/lib/cli.js:100890:78)
    at Object.findRc (/home/holger/.nvm/versions/node/v12.13.1/lib/node_modules/yarn/lib/cli.js:100904:10)
    at getRcConfigForCwd (/home/holger/.nvm/versions/node/v12.13.1/lib/node_modules/yarn/lib/cli.js:56916:74)
    at /home/holger/.nvm/versions/node/v12.13.1/lib/node_modules/yarn/lib/cli.js:92255:56
    at Generator.next (<anonymous>)
    at step (/home/holger/.nvm/versions/node/v12.13.1/lib/node_modules/yarn/lib/cli.js:310:30)

~/w/lineupjs/lineupjs sgratzl/upgrade ?1                                                          
```

I had a look for the error and [StackOverflow suggests](https://stackoverflow.com/questions/62851183/yarn-fails-with-typeerror-cannot-read-property-yarnpath-of-null) to install yarn using apt-get or removing the `yarnPath` from the _.yarnrc_.

Removing the `yarnPath` or the whole _.yarnrc_ file did not work for me and results in the same error on `yarn install`. 

@sgratzl Any suggestion what could be wrong here? Is there anything I'm missing?

2021-03-08 10:03 UTC, sgratzl commented
see also:

https://github.com/lineupjs/lineupjs/pull/410/files/fb5bb6d000be9cd58b995b2be1f52d51c5c7e118..248c9a3d356fd4f36f8b7fcea9fa248735674b05

the procedure to get the latest berry version isn't that obvious:

```
yarn set version berry
yarn set version latest
yarn install
```

2021-03-08 10:05 UTC, thinkh commented
Thanks for the quick fix. No, the command wasn't obvious, but the berry command fixes my error above. I will continue the setup and review.

2021-03-08 10:30 UTC, thinkh requested changes
Testing the [common (yarn) commands](https://github.com/lineupjs/lineupjs/blob/sgratzl/upgrade/README.md#common-commands):

```
✔ yarn start
✔ yarn clean
✔ yarn compile
❌ yarn test
⚠ yarn lint
✔ yarn fix
✔ yarn build
✔ yarn docs
yarn release (not tested)
yarn release:pre (not tested)
```

----

❌ yarn test

```
❯ yarn test
 FAIL  tests/internal/merge.spec.ts
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/en/ecmascript-modules for how to enable it.
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    /home/holger/w/lineupjs/lineupjs/src/internal/merge.js:7
    export default function merge(target, source) {
    ^^^^^^

    SyntaxError: Unexpected token 'export'

    > 1 | import merge from '../../src/internal/merge';
        | ^
      2 |
      3 | describe('merge', () => {
      4 |   it('empty', () => {

      at Runtime.createScriptFromCode (.yarn/cache/jest-runtime-npm-26.6.3-bf7a869586-5ef4ceaefb.zip/node_modules/jest-runtime/build/index.js:1350:14)
      at Object.<anonymous> (tests/internal/merge.spec.ts:1:1)

 FAIL  tests/builder/DataBuilder.spec.ts
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/en/ecmascript-modules for how to enable it.
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    /home/holger/w/lineupjs/lineupjs/src/builder/DataBuilder.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import * as tslib_1 from "tslib";
                                                                                             ^^^^^^

    SyntaxError: Cannot use import statement outside a module

    > 1 | import { DataBuilder } from '../../src/builder/DataBuilder';
        | ^
      2 | import { IColumnDesc, Column, ITypeFactory } from '../../src/model';
      3 |
      4 | interface IMyCustomDesc extends IColumnDesc {

      at Runtime.createScriptFromCode (.yarn/cache/jest-runtime-npm-26.6.3-bf7a869586-5ef4ceaefb.zip/node_modules/jest-runtime/build/index.js:1350:14)
      at Object.<anonymous> (tests/builder/DataBuilder.spec.ts:1:1)

 FAIL  tests/internal/accessor.spec.ts
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/en/ecmascript-modules for how to enable it.
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    /home/holger/w/lineupjs/lineupjs/src/internal/accessor.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import get from 'lodash.get';
                                                                                             ^^^^^^

    SyntaxError: Cannot use import statement outside a module

    > 1 | import { rowComplexGetter } from '../../src/internal/accessor';
        | ^
      2 |
      3 | function get(v: any, column: string) {
      4 |   return rowComplexGetter({ i: 0, v }, { column });

      at Runtime.createScriptFromCode (.yarn/cache/jest-runtime-npm-26.6.3-bf7a869586-5ef4ceaefb.zip/node_modules/jest-runtime/build/index.js:1350:14)
      at Object.<anonymous> (tests/internal/accessor.spec.ts:1:1)

 FAIL  tests/model/internal.spec.ts
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/en/ecmascript-modules for how to enable it.
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    /home/holger/w/lineupjs/lineupjs/src/model/internal.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import * as tslib_1 from "tslib";
                                                                                             ^^^^^^

    SyntaxError: Cannot use import statement outside a module

    > 1 | import { unifyParents } from '../../src/model/internal';
        | ^
      2 | import { IGroupParent, IOrderedGroup } from '../../src/model';
      3 |
      4 | function groupGen(name: string, parent?: IGroupParent): IOrderedGroup {

      at Runtime.createScriptFromCode (.yarn/cache/jest-runtime-npm-26.6.3-bf7a869586-5ef4ceaefb.zip/node_modules/jest-runtime/build/index.js:1350:14)
      at Object.<anonymous> (tests/model/internal.spec.ts:1:1)

 FAIL  tests/browser.spec.ts
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/en/ecmascript-modules for how to enable it.
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) yo [...]

2021-03-08 10:37 UTC, sgratzl commented
re tests: 
 * there shouldn't be any *.js files in your src folder anymore
re linting:
 * I don't know what your git settings are regarding line endings

all work, see also https://github.com/lineupjs/lineupjs/runs/2055459628?check_suite_focus=true

2021-03-08 10:40 UTC, thinkh requested changes

2021-03-08 10:40 UTC, thinkh commented on README.md
> +yarn run cy:open
1. Replace with `yarn` only?
2. `yarn run build:prod` script does not exists

2021-03-08 10:40 UTC, thinkh commented on README.md
> +yarn run cy:start
Replace with `yarn` only?

2021-03-08 10:40 UTC, thinkh commented on README.md
> +yarn run watch
Replace with `yarn` only?

2021-03-08 10:43 UTC, thinkh commented
> re tests:
> 
>     * there shouldn't be any *.js files in your src folder anymore
>       re linting:
> 
>     * I don't know what your git settings are regarding line endings
> 
> 
> all work, see also [lineupjs/lineupjs/runs/2055459628?check_suite_focus=true](https://github.com/lineupjs/lineupjs/runs/2055459628?check_suite_focus=true)

Yes, true. I removed all .js files in the build and test folder and ran `yarn test` again. Now everything is green. 👍

2021-03-08 10:45 UTC, thinkh commented
Out of curiosity, since you changed your commit message style. Is there a reference for this?

2021-03-08 14:11 UTC, sgratzl commented on README.md
> +yarn run watch
for documentation reason I prefer the `yarn run` version to ensure it will run the script. e.g. there is a `prettier` exec and a `prettier` script

2021-03-08 15:09 UTC, sgratzl commented
> Out of curiosity, since you changed your commit message style. Is there a reference for this? And what is the advantage?

it is loosely based on https://www.conventionalcommits.org/en/v1.0.0-beta.2/#summary. The advantages are that they are more machine readable what the change is about and adds a classification to the commit message. it can be used for automatic changelog generation or automatic versioning

2021-03-23 10:27 UTC, thinkh approved these changes
Sorry, I missed to accept this PR. Now it looks all good to me. You can go ahead and merge this PR into develop. Thanks.

2021-03-23 11:56 UTC, merged