add possibility to hide nested column headers
lineupjs/lineupjs pull request #412
Opened 2021-02-27 17:09 UTC by sgratzl

closes #395

**Prerequisites**:

* [x] Branch is up-to-date with the branch to be merged with, i.e. develop
* [x] Build is successful
* [x] Code is cleaned up and formatted 
* [x] Tested with Firefox ESR, latest Firefox, latest Chrome, Edge 18

### Summary
 
the nested header will only be shown if the default summary renderer is selected:

before:

http://localhost:8080/nested_bug_pr133.html

with e.g., grouped histogram stack renderer:

![image](https://user-images.githubusercontent.com/4129778/109394364-e73a2e00-7926-11eb-930b-a577d877366e.png)

2021-03-08 12:11 UTC, thinkh approved these changes
Works for me as expected.

@puehringer Please review as well. We can discuss this PR also tomorrow morning.

2021-03-09 09:39 UTC, thinkh requested changes
Default status

![grafik](https://user-images.githubusercontent.com/5851088/110450511-8eeff280-80c3-11eb-8900-c94fee882ed5.png)

Switch renderer to `nested` hides the summary and is equal to `none`

![grafik](https://user-images.githubusercontent.com/5851088/110450674-b3e46580-80c3-11eb-98a6-a1314dec29c1.png)

2021-03-09 09:39 UTC, thinkh commented on src/ui/MultiLevelRenderColumn.ts
> +    const sub = this.mc.getSummaryRenderer() !== this.mc.desc.summaryRenderer ? [] : this.mc.children;
Is this correct? Since `this.mc.desc.summaryRenderer` can be set when creating the column (desc). This check will only be true when the user changes the visualization? What happens if the user passes a boxplot summary renderer in the column description and changes the visualization in the UI to stacked bar renderer? Then the condition will be true and no children will be renderered even though it should render the children. 

`mc.desc.summaryRenderer = 'boxplot'`
![grafik](https://user-images.githubusercontent.com/5851088/110450004-11c47d80-80c3-11eb-8d3c-7277653e9e84.png)

Switch in visualization to `stack` renderer
![grafik](https://user-images.githubusercontent.com/5851088/110450105-302a7900-80c3-11eb-8254-392223383bb1.png)

The solution might be probably to add another `rendererChildrenSummary` in the stacked column desc.

2021-03-10 15:19 UTC, sgratzl commented on src/ui/MultiLevelRenderColumn.ts
> +    const sub = this.mc.getSummaryRenderer() !== this.mc.desc.summaryRenderer ? [] : this.mc.children;
how can the user interactively change this option then?

2021-03-11 08:00 UTC, thinkh commented on src/ui/MultiLevelRenderColumn.ts
> +    const sub = this.mc.getSummaryRenderer() !== this.mc.desc.summaryRenderer ? [] : this.mc.children;
> how can the user interactively change this option then?

The user can currently not switch it. It would require another toggle button in the UI where the user can turn the nested headers on or off. Since this is probably too much effort to implement this UI, it would be sufficient if the developer can explicitly define in the column description if the nested headers should be visible or not.

2021-03-22 20:50 UTC, sgratzl commented on src/ui/MultiLevelRenderColumn.ts
> +    const sub = this.mc.getSummaryRenderer() !== this.mc.desc.summaryRenderer ? [] : this.mc.children;
see the new `nestedSummary.html` demo

2021-04-08 22:41 UTC, sgratzl commented on src/ui/MultiLevelRenderColumn.ts
> +    const sub = this.mc.getSummaryRenderer() !== this.mc.desc.summaryRenderer ? [] : this.mc.children;
ping

2021-04-09 08:40 UTC, thinkh commented on src/ui/MultiLevelRenderColumn.ts
> +    const sub = this.mc.getSummaryRenderer() !== this.mc.desc.summaryRenderer ? [] : this.mc.children;
Looks good now! 👍

2021-04-09 08:46 UTC, thinkh requested changes
I would just remove the comment since the code is clearer now. The rest looks good.

2021-04-09 08:46 UTC, thinkh commented on src/ui/MultiLevelRenderColumn.ts
> +    // hide the children when not the default summary is shown = which is none
```suggestion
```

This comment can be removed.

2021-04-09 17:49 UTC, thinkh approved these changes

2021-04-09 18:42 UTC, merged