Update to Fontawesome 5
lineupjs/lineupjs pull request #478
Opened 2021-08-24 14:55 UTC by sgratzl

closes #402 , based on #477 

**prerequisites**:

- [x] branch is up-to-date with the branch to be merged with, i.e. develop
- [x] build is successful
- [x] code is cleaned up and formatted

## Summary

updates to Fontawesome 5 free as good as it gets

2021-08-24 20:51 UTC, thinkh reviewed
The netlify preview shows still the FontAwesome 4. Is this intentional? Why don't we make FontAwesome 5 the default and drop FA 4?

2021-08-24 20:51 UTC, thinkh commented on src/styles/_vars.scss
>  $lu_use_font_awesome: false !default;
Do I understand this PR correctly, that by default LineUp is still using Fontawesome 4 (via custom lu-font)? And if somebody wants to have FontAwesome 5 he/she must change the flag and add the imports as described in the comments?

2021-08-24 21:09 UTC, thinkh requested changes
I'm testing this PR now locally and I'm able to see the FA 5 icons after uncommenting the respective lines in _vars.scss.

Can we keep the column type icons also with FA 5? 

**Before (with FA 4)**

![grafik](https://user-images.githubusercontent.com/5851088/130689541-2504a0a7-ac6f-44c7-a1a7-90d659dc382d.png)

**After (with FA 5)**

![grafik](https://user-images.githubusercontent.com/5851088/130689719-89935a39-bf31-4341-a668-e886e0927f30.png)

[The icons are also available as SVG in the assets folder](https://github.com/lineupjs/lineupjs/tree/sgratzl/fontawesome5/src/assets). So we can either use the SVG or create a custom font with only the icons (instead of the ones included in the lu-font).

2021-08-24 21:47 UTC, thinkh commented
I cannot figure out how to use FA 5 outside of LineUp with the current PR state. 

1. Checkout this PR
2. `yarn run build:dev`

The `build` contains only the `LineUpJS.css` file, but no SASS file.

![grafik](https://user-images.githubusercontent.com/5851088/130693736-6111956b-5c0d-4ec2-9aea-dc0e686a4252.png)

Importing the `LineUpJS.css` file in a different app/project still shows the FA 4 icons.

In my opinion we have now the following options:

1. Create a custom build with `$lu_use_font_awesome: true` -> probably not the way to go when using LineUp as a library
2. Generate additional SCSS files that can imported in a different app/project after setting `$lu_use_font_awesome: true`
3. Use FA 5 as LineUp default icons

@sgratzl Could you please generate the SCSS files or use FA 5 as default icons? Thanks.

2021-09-13 22:09 UTC, thinkh commented
> I updated the custom font also to use Font Awesome 5 (see README notes about using [fontello/fontello#665](https://github.com/fontello/fontello/pull/665)).

Thanks, that looks good after switching the flag `$lu_use_font_awesome` to true.

> I guess so far the method is to build the style sheet from source directly. Part of the package should be the src/styles.scss which you can import in your setup and change variables before. (similar what tdp_core is doing)

Yes, true that would be the solution. Unfortunately, it does not work for us in tdp_core, due to the different sass compilers (LineUp = Dart Sass; tdp_core = Node Sass):

![grafik](https://user-images.githubusercontent.com/5851088/133162907-ad94dddb-822b-43cf-8666-dc7e51c62c19.png)

2021-09-14 14:39 UTC, sgratzl commented
I added a built artifact: `LineUpJS_fontawesome.css` which is a style sheet version with the font awesome flag enabled. Moreover, I disabled by default that the Font awesome files are bundled, so one has to provide them manually, see also `demo/fontawesome.html`

2021-11-19 15:58 UTC, sgratzl commented
@thinkh ping

2021-11-23 08:39 UTC, thinkh approved these changes

2021-11-23 13:10 UTC, merged