Taggle overview mode
lineupjs/lineupjs pull request #552
Opened 2022-03-15 14:11 UTC by sgratzl

closes #551

**prerequisites**:

- [x] branch is up-to-date with the branch to be merged with, i.e. develop
- [x] build is successful
- [x] code is cleaned up and formatted

## Summary

refactor overview mode toggle to be set via `setOverviewMode`. In addition, allow to disable the side panel within Taggle

2022-04-06 10:49 UTC, puehringer requested changes

2022-04-06 10:49 UTC, puehringer commented on src/ui/taggle/Taggle.ts
> +    return this.renderer?.getRule() == this.spaceFillingRule;
I suppose the Github Action with the warning `Expected '===' and instead saw '=='` is correct and should be fixed?

2022-04-07 13:27 UTC, sgratzl commented on src/ui/taggle/Taggle.ts
> +    return this.renderer?.getRule() == this.spaceFillingRule;
fixed

2022-04-11 06:58 UTC, puehringer approved these changes
Looks good to me! 🎉

2022-04-11 12:50 UTC, merged