feat: change key for detecting duplicates
lineupjs/lineupjs pull request #632
Opened 2023-08-01 01:57 UTC by sgratzl

closes #630

**prerequisites**:

- [x] branch is up-to-date with the branch to be merged with, i.e. develop
- [x] build is successful
- [x] code is cleaned up and formatted

## Summary

implement patch as suggested

2023-08-01 08:49 UTC, dvmartinweigl requested changes

2023-08-01 08:49 UTC, dvmartinweigl commented on src/builder/DataBuilder.ts
I think you should also add the summary to `oldPos` lookup in line 174

2023-08-01 15:50 UTC, thinkh commented on src/builder/DataBuilder.ts
> +      const key = `${c.type}@${c.label}@${c.summary}`;
Do we also need to change line 174 below?

2023-08-02 07:06 UTC, thinkh approved these changes
Thanks for the quick fix.

2023-08-02 07:15 UTC, merged